apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress-nginx
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: '3.31.0'
    helm:
      valueFiles:
        - ../values/nginx.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
